### ISSUE TITLE
Main activity should not display near empty categories

### ISSUE THREAD

**Issue by scsole** [sthoray/AllRight#11]
Some top level categories have only 10 listing in! We should reduce the number of displayed categories on the landing page.

**Comment by muljo** [comment]
Can't we just sort the categories by how many listings they have

**Comment by scsole** [comment]
If we added sorting to categories, I would strongly suggest it remains as an option which is disabled by default.
Imagine if someone used the app everyday to look for certain items. If the list was sorted by default, the order could change every day making it frustrating to locate categories as they would not be consistent.

**Comment by scsole** [comment]
It turns out that there is actully a different request for the featured page: `categoryFeaturePanel`. This returns a much smaller list along with image URLs!

The `category/topLevel` request will actually be used in the browse activity.
