### ISSUE TITLE
Add support for switching between Mall and Second Hand

### ISSUE THREAD

**Issue by muljo** [sthoray/AllRight#27]
The user shall be able to switch between the “Mall” (Firsthand) and secondhand stores.

**Comment by scsole** [comment]
As a general rule of thumb, the searh query should contain:

- Mall
    - auctions=0
    - products=1
- Second hand:
    - auctions=1
    - products=0

However, there are exceptions to this which should be sorted out for the beta. For example, vehicles has both properties set to 1.
