### ISSUE TITLE
Display item specifics in the Listing Activity

### ISSUE THREAD

**Issue by scsole** [sthoray/AllRight#88]
### Is your feature request related to a problem? Please describe

While we can retrieve item specifics, we currently do not display them in the `Listing Activity`

### Describe the solution you'd like

- [x] Add views for item specifics in `ListingActivity`
- [x] Populate view with item specifics
- [x] Only use as much space as required for provided item specifics

**Comment by bjmccarthy1993** [comment]
There are 6 Values returned in the properties (item specifics). They are: Title, Option, ID, Option ID, Type and Value. Of these, Title and Option appear to be the most relevant most of the time. Option ID appears to only have a value (an Int) when Option does, and ID and Type appear to be just Ints so aren't particularly interesting. However Value is quite unpredictable, sometimes having relevant data, sometimes being null, and sometimes being just an Int. Unsure as to why this is

**Comment by scsole** [comment]
I also think `id` and `optionId` can essentially be ignored for our use. During my initial observation I found `type` to actually be quite interesting. I think `type` should be used to determine if `option` or `value` should be used. When `type=1`, the description of the property is contained in `option`. Likewise, when `type=2`, `value` becomes the data source. This is all already documented in our code but I'm happy to investigate further if this turns out to be incorrect. I'll admit, I didn't take a large sample size when making my predictions :)
