### ISSUE TITLE
Resource error constants

### ISSUE THREAD

**Issue by muljo** [sthoray/AllRight#95]
I'm always frustrated when I have to type out the error messages manually when testing my code to make sure they match they error messages in production code.  
  
e.g. "No internet connection" in the ViewModels

#### Proposed Solution
  
Create an enum in the Resource.Error subclass that holds constants for the different resource error messages

**Comment by scsole** [comment]
I agree. Since these custom error messages are also displayed to the user, the actual strings should rather be stored as a resource. This would allow for easier translations to be done at some point.
